export const prompts = [
  "What was the most unexpected thing that happened to you this week?",
  "Describe a time when you tried something new. How did it go?",
  "What’s your favorite memory from the past year?",
  "If you could visit any place in the world, where would you go and why?",
  "What’s the most interesting conversation you’ve had recently?",
  "Describe a hobby you enjoy and how you got into it.",
  "What’s the most important lesson you’ve learned recently?",
  "If you could relive any day of your life, which day would you choose and why?",
  "What’s something you’ve been thinking about a lot lately?",
  "Tell us about a time when you helped someone. How did it make you feel?",
  "What’s a goal you’re currently working towards?",
  "Describe a time when you were really proud of yourself.",
  "What’s a skill you’ve always wanted to learn and why?",
  "What’s the best piece of advice you’ve ever given to someone?",
  "What’s something that always puts you in a good mood?",
  "Describe your ideal weekend. What would you do?",
  "What’s a challenge you’ve faced recently and how did you deal with it?",
  "What’s something you’re really passionate about and why?",
  "Tell us about a time when you surprised yourself.",
  "What’s a habit you’re trying to build or break?",
  "What’s a favorite family tradition and why is it special to you?",
  "Describe a memorable meal you’ve had. What made it unforgettable?",
  "What’s a personal achievement that means a lot to you?",
  "If you could meet any historical figure, who would it be and why?",
  "What’s a book or movie that had a significant impact on your life?",
  "Share a time when you had to step up as a leader. What did you learn?",
  "What’s a topic you could talk about for hours and why?",
  "Describe an experience that made you see things differently.",
  "What’s a place you’ve always wanted to visit and why?",
  "Tell us about a time when you faced a fear and overcame it.",
  "What’s a recent accomplishment you’re proud of?",
  "Describe a meaningful gift you’ve received. Why was it special?",
  "What’s a cause you’re passionate about and how do you support it?",
  "If you could change one thing about your daily routine, what would it be and why?",
  "What’s a lesson you’ve learned from a mistake?",
  "Describe a time when you had to work with someone who had a different perspective.",
  "What’s a piece of advice you would give to your younger self?",
  "What’s the most interesting thing you’ve learned recently?",
  "Share a story about a time when you helped a friend in need.",
  "What’s a goal you’ve set for yourself this year and how are you working towards it?",
  "Describe a favorite childhood memory and what makes it special.",
  "What’s a passion of yours that you haven’t had time to pursue recently?",
  "Tell us about a time when you had to adapt to a significant change.",
  "What’s something you’re grateful for today?",
  "Describe a time when you had to solve a problem creatively.",
  "What’s a hobby or interest that you think others should try?",
  "What’s a recent experience that made you laugh out loud?",
  "If you could live anywhere in the world, where would it be and why?",
  "What’s a skill you’re currently working on and why?",
  "Describe a time when you felt truly at peace.",
  "What’s a new habit you’ve developed recently and how has it affected you?",
  "Tell us about a person who has had a significant influence on your life.",
  "What’s a favorite quote or saying that inspires you?",
  "Describe a moment when you felt completely out of your comfort zone.",
  "What’s a memorable project you’ve worked on and what did you learn from it?",
  "What’s a recent book or article you read that you would recommend?",
  "What’s something you’ve done that you’re really proud of?",
  "Describe a time when you learned something surprising about yourself.",
  "What’s a tradition you’d like to start with your friends or family?",
  "Tell us about a time when you had to make a tough decision.",
  "What’s something new you’ve tried recently and how did it go?",
  "Describe a time when you felt really connected to someone.",
  "What’s a place you’d like to explore and why?",
  "What’s a personal goal you’ve achieved and how did you reach it?",
  "What’s a challenge you’re currently facing and how are you handling it?",
  "Describe an experience that taught you a valuable lesson.",
  "What’s a favorite way to spend your free time and why?",
  "Tell us about a time when you felt really inspired.",
  "What’s a habit or routine that helps you stay productive?",
  "Describe a memorable event that brought you joy.",
  "What’s a recent achievement you’re excited about?",
  "What’s a topic you’re passionate about and why?",
  "Tell us about a time when you had to learn something quickly.",
  "What’s a favorite place you like to visit and why?",
  "Describe a situation where you had to think on your feet.",
  "What’s something you’ve done recently that made you happy?",
  "Tell us about a person who has had a significant impact on your life.",
  "What’s a recent experience that made you feel accomplished?",
  "Describe a time when you felt really understood by someone.",
  "What’s a favorite way to relax and unwind?",
  "What’s a recent goal you’ve set for yourself and how are you working towards it?",
  "Tell us about a time when you had to overcome a significant obstacle.",
  "What’s a passion project you’d like to start and why?",
  "Describe a time when you had to navigate a difficult situation.",
  "What’s something you’re looking forward to in the near future?",
  "What’s a recent change you’ve made that has improved your life?",
  "Tell us about a time when you felt truly happy.",
  "What’s a favorite hobby or activity that you enjoy?",
  "Describe an experience that challenged your perspective.",
  "What’s a personal value that guides your decisions?",
  "What’s a recent project you’ve worked on and what did you learn from it?",
  "Tell us about a time when you felt really proud of someone else.",
  "What’s a goal you’re passionate about and why?",
  "Describe a time when you felt completely in your element.",
  "What’s something you’ve learned from a recent experience?",
  "Tell us about a place you’ve visited that left a lasting impression on you.",
  "What’s a favorite memory from your childhood and why?",
  "Describe a recent experience that made you feel grateful.",
  "What’s a skill you’re developing and how are you progressing?",
  "Tell us about a time when you had to adapt to a new situation.",
  "What’s a recent accomplishment that made you feel proud?",
  "What’s a favorite way to spend time with friends or family?",
  "Describe a situation where you had to overcome a fear.",
  "What’s something new you’d like to learn and why?",
  "Tell us about a time when you felt a strong sense of achievement.",
  "What’s a recent experience that made you reflect on your values?",
  "Describe a time when you felt truly motivated.",
  "What’s a personal goal you’re working towards and what steps are you taking?",
  "Tell us about a place that has special significance to you.",
  "What’s a favorite tradition or ritual that you cherish?",
  "Describe a recent challenge you faced and how you addressed it.",
  "What’s something you’re excited about in the near future?",
  "Tell us about a time when you learned something new about yourself.",
  "What’s a favorite activity or pastime that brings you joy?",
  "Describe an experience that had a major impact on your life.",
  "What’s a recent success you’re proud of and why?",
  "Tell us about a person who inspires you and why.",
  "What’s a recent change you’ve made that has positively impacted your life?",
  "Describe a time when you felt a deep sense of accomplishment.",
  "What’s a goal you’re passionate about and what motivates you to pursue it?",
  "Tell us about a recent experience that challenged your thinking.",
  "What’s a favorite memory with friends or family and why is it special?",
  "Describe a time when you had to persevere through a difficult situation.",
  "What’s a recent achievement that has made a difference in your life?",
  "Tell us about a time when you felt truly inspired by someone else.",
  "What’s a personal value that’s important to you and why?",
  "Describe a time when you felt completely immersed in an activity.",
  "What’s a favorite way to unwind after a busy day?",
  "Tell us about a place that makes you feel relaxed and why.",
  "What’s a recent goal you’ve set and how are you making progress?",
  "Describe a time when you felt a strong sense of community.",
  "What’s a passion or interest that you’re currently pursuing?",
  "Tell us about a time when you had to overcome a major obstacle.",
  "What’s a recent experience that made you appreciate something more?",
  "Describe a time when you felt truly connected to others.",
  "What’s a favorite way to spend a day off and why?",
  "Tell us about a person who has had a positive impact on your life.",
  "What’s a recent accomplishment that has made you feel fulfilled?",
  "Describe a time when you had to adapt to unexpected changes.",
  "What’s a goal you’re excited about and how are you working towards it?",
  "Tell us about a recent experience that made you reflect on your goals.",
];
